### ISSUE TITLE
Integrate Google Flights

### ISSUE THREAD

**Issue by jeancsil** [jeancsil/flight-spy#3]
Use this documentation and see the availability to implement the API.

https://developers.google.com/qpx-express/v1/trips#resource

**Comment by infiBoy** [comment]
404 :(

**Comment by jeancsil** [comment]
Hey @infiBoy ,
I'll deprecate this repo. Unfortunately is not as easy as it used to be to have a dev account in Skyscanner, so the work I did since then isn't useful anymore.
